// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Tokens struct {
	Access  string `json:"access"`
	Refresh string `json:"refresh"`
}

type UserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
